12865 yji0828
buzri1905/algo_study pull request #15
Opened 2021-08-27 03:50 UTC by wjddls0828

이전 커밋들이 같이 들어갔네용....ㅠㅠ
12865만 봐주세용!

2021-09-05 04:08 UTC, wjddls0828 commented on codes/12865_cpp_yji0828.cpp
> +int dp[101][100001];
반영했습니다!

2021-09-06 13:39 UTC, buzri1905 requested changes
피드백 확인해주세요

2021-09-06 13:39 UTC, buzri1905 commented on codes/1963_cpp_yji0828.cpp
> +				if (j == (cur / i)%10)
이건 지워주세요
```suggestion
```

2021-09-06 13:39 UTC, buzri1905 commented on codes/1963_cpp_yji0828.cpp
> +				if (j == (cur / i) % 10)
/ % *는 왼쪽부터 연산해서 괄호를 안써도 됩니다.
```suggestion
				if (j == cur / i % 10)
```

2021-09-06 13:39 UTC, buzri1905 commented on codes/1963_cpp_yji0828.cpp
> +				next = cur + (j * i) - ((cur % (i * 10)) / i) * i;
괄호가 많으면 가독성이 떨어집니다.
```suggestion
				next = cur + j * i - cur % i * 10 / i * i;
```

2021-09-06 13:39 UTC, buzri1905 commented on codes/1963_cpp_yji0828.cpp
> +#include <cmath>
사용하지 않는 헤더파일은 지워주세요
```suggestion
```

2021-09-06 13:39 UTC, buzri1905 commented on codes/9465_cpp_yji0828.cpp
> +#define _CRT_SECURE_NO_WARNINGS
이건 지워주세요
```suggestion
```

2021-09-06 14:31 UTC, merged

2021-09-06 14:31 UTC, buzri1905 commented
머지했습니다.