9184_py3_sjskgks.py is modified
buzri1905/algo_study pull request #24
Opened 2021-08-29 04:35 UTC by sjskgks

리뷰에따라 메모이제이션을 사용해 다시 풀었습니다.

2021-09-03 14:30 UTC, buzri1905 requested changes
피드백 확인해주세요

2021-09-03 14:30 UTC, buzri1905 commented on codes/9184_py3_sjskgks.py
> +        pass
pass는 아무것도 하지 않습니다.
https://docs.python.org/ko/3/tutorial/controlflow.html
바로 return하는게 더 좋아보입니다.
```suggestion
        return log[a][b][c]
```

2021-09-03 14:30 UTC, buzri1905 commented on codes/9184_py3_sjskgks.py
> +        log[a][b][c]=1
이럴때도 대입하지 않고 바로 리턴해도 됩니다.
```suggestion
        return 1
```

2021-09-03 14:30 UTC, buzri1905 commented on codes/9184_py3_sjskgks.py
> +            sub_a, sub_b, sub_c = 20, 20, 20
이 예외처리를 memoization 함수 안에서 해주세요

2021-09-03 17:31 UTC, sjskgks commented on codes/9184_py3_sjskgks.py
> +        log[a][b][c]=1
a==0 or b==0 or c==0인 경우에 처음방식대로 log에 저장해놓으면 if log[a][b][c]!=-1: return log[a][b][c]에서 바로 리턴이되는데 리뷰해주신 방식으로 하면 작동은 잘 하지만 log에 저장은 안돼서 아래 elif a==0 or b==0 or c==0: return 1부분으로 가서 한번 더 이프문을 봐야하지 않나요? (여기서 pass대신 피드백 주신대로 return log[a][b][c]바꿨을 떄의 이야기 입니당)

2021-09-03 17:35 UTC, sjskgks commented on codes/9184_py3_sjskgks.py
> +        log[a][b][c]=1
이 부분은 선택사항으로 리뷰해주신거같아서 해당 부분은 그냥 저장하는 식으로 하겠습니다!

2021-09-04 11:15 UTC, merged

2021-09-04 11:15 UTC, buzri1905 commented
머지했습니다.