Create 1965_cpp_dbstn322.cpp
buzri1905/algo_study pull request #26
Opened 2021-09-09 02:19 UTC by yslee96

1965번 풀이 제출입니다.

(PR은 이렇게 하면 되는거죠? 문제 풀이보다 이거 터득하는게 조금 더 걸린듯 ㅋㅋ)

2021-09-09 08:47 UTC, buzri1905 requested changes
피드백 확인해주세요

2021-09-09 08:47 UTC, buzri1905 commented on codes/1965_cpp_dbstn322.cpp
> +    int box[n];
이거 C에서는 허용안되는 문법인거 아시죠? 지금은 C++이여서 가능하긴 합니다.

2021-09-09 08:47 UTC, buzri1905 commented on codes/1965_cpp_dbstn322.cpp
> +    }
```suggestion
        cin >> box[i];
```

2021-09-09 08:47 UTC, buzri1905 commented on codes/1965_cpp_dbstn322.cpp
> +    int max = 0;
max라는 이름의 스탠다드 함수가 있습니다. maximum 같은 변수명을 사용하는 편이 나중에 편할 것 같습니다.

2021-09-09 08:47 UTC, buzri1905 commented on codes/1965_cpp_dbstn322.cpp
> +        }
만약 algorithm 헤더파일을 인클루드해서 max 함수를 쓴다면 다음과 같이 간략하게 쓸 수 있습니다.
```suggestion
            if (box[j] < box[i])
                dp[i] = max(dp[i], dp[j] + 1);
```

2021-09-09 13:06 UTC, yslee96 commented on codes/1965_cpp_dbstn322.cpp
> +    int box[n];
넵 C에서는 dp처럼 배열 크기 먼저 선언해두고 입력 받는 걸로 알고 있습니다. 반영하겠습니다!

2021-09-09 13:07 UTC, yslee96 commented on codes/1965_cpp_dbstn322.cpp
> +    }
아 어쩐지...!!! 감사합니다

2021-09-09 13:07 UTC, yslee96 commented on codes/1965_cpp_dbstn322.cpp
> +        }
넵 반영하겠습니다! 더 간단해지네요

2021-09-14 15:21 UTC, buzri1905 approved these changes
고생하셨습니다

2021-09-14 15:22 UTC, merged