1916_cpp_dbstn322.cpp
buzri1905/algo_study pull request #27
Opened 2021-09-13 15:30 UTC by yslee96

1916번 PR 입니다

2021-09-14 15:25 UTC, buzri1905 requested changes
피드백 확인해주세요

2021-09-14 15:25 UTC, buzri1905 commented on codes/1916_cpp_dbstn322.cpp
> +priority_queue<pair<int, int>> shortDist;
<,>를 2번 이상 연속으로 쓰면 컴파일러가 비트연산으로 잘못처리해서 컴파일 에러가 날 수 있습니다.
```suggestion
vector<pair<int, int> > edges[100001];
priority_queue<pair<int, int> > shortDist;
```

2021-09-14 15:25 UTC, buzri1905 commented on codes/1916_cpp_dbstn322.cpp
> +        for (vector<pair<int, int>>::iterator iter = edges[node].begin(); iter != edges[node].end(); iter++)
여기도 수정해주세요
```suggestion
        for (vector<pair<int, int> >::iterator iter = edges[node].begin(); iter != edges[node].end(); iter++)
```

2021-09-14 15:25 UTC, buzri1905 commented on codes/1916_cpp_dbstn322.cpp
> +}
return 0꼭해주세요
```suggestion
    return 0;
}
```

2021-10-01 01:30 UTC, yslee96 commented
반영했습니다. 피드백 감사합니다!

2021-10-01 01:33 UTC, yslee96 commented
return 0 넣은게 반영이 안됐네요 다시 올렸습니다.

2021-10-01 10:55 UTC, merged

2021-10-01 10:55 UTC, buzri1905 commented
고생하셨습니다!