13424_cpp_dbstn322.cpp (reupload)
buzri1905/algo_study pull request #32
Opened 2021-09-21 14:17 UTC by yslee96

13424번 재업입니다.

2021-09-21 14:23 UTC, buzri1905 requested changes
각 node에 대해 다익스트라를 돌리는 것보다 플로이드 와샬이 시간복잡도 적으로도 구현 코드량으로도 더 유리합니다. 플로이드 와샬로 풀어보시겠어요?

2021-09-22 06:22 UTC, yslee96 commented
> 각 node에 대해 다익스트라를 돌리는 것보다 플로이드 와샬이 시간복잡도 적으로도 구현 코드량으로도 더 유리합니다. 플로이드 와샬로 풀어보시겠어요?

다시 올렸습니다!

2021-09-22 11:49 UTC, buzri1905 requested changes
피드백 확인해주세요

2021-09-22 11:49 UTC, buzri1905 commented on codes/13424_cpp_dbstn322.cpp
> +int sumOfDists[102];
이건 main안에 있어도 괜찮을 것 같습니다.

2021-09-22 11:49 UTC, buzri1905 commented on codes/13424_cpp_dbstn322.cpp
> +            for(int j=1; j<=101; j++){
코드 스타일은 하나로 통일해주세요
```suggestion
        for(int i=1; i<=101; i++)
        {
            for(int j=1; j<=101; j++)
            {
```

2021-09-22 11:49 UTC, buzri1905 commented on codes/13424_cpp_dbstn322.cpp
> +            for(int i=1; i<=numOfRooms; i++){
여기도 통일해주세요
```suggestion
            for(int i=1; i<=numOfRooms; i++)
            {
```

2021-09-22 11:49 UTC, buzri1905 commented on codes/13424_cpp_dbstn322.cpp
> +        }
```suggestion
        int result = sumOfDists[1];
        int roomNum = 1;

        for (int i = 2; i <= numOfRooms; i++)
        {
            if (sumOfDists[i] < result)
            {
                result = sumOfDists[i];
                roomNum = i;
            }
        }
```

2021-09-22 11:49 UTC, buzri1905 commented on codes/13424_cpp_dbstn322.cpp
> +        printf("%d\n", num);
위 피드백 반영하시면 여기도 roomNum으로 고쳐주세요

2021-10-01 01:21 UTC, yslee96 commented
피드백 반영해서 다시 수정했습니다. 훨씬 나아졌네요! 감사합니다 👍

2021-10-01 07:43 UTC, buzri1905 approved these changes

2021-10-01 07:43 UTC, merged

2021-10-01 07:43 UTC, buzri1905 commented
고생하셨습니다!