Create 1963_cpp_wodnjs.cpp
buzri1905/algo_study pull request #6
Opened 2021-08-19 01:45 UTC by resource777

다시  PR 올렸습니다.

2021-08-22 03:41 UTC, buzri1905 requested changes
피드백 반영해주세요

2021-08-22 03:41 UTC, buzri1905 commented on codes/1963_cpp_wodnjs.cpp
> +			cout << vis[to] - 1 << '\n';
vis를 참고하기보다 bfs_ret값을 출력하게끔하는게 좋을 것 같습니다.
그러면 bfs의 return값도 수정하게 해야겠죠?

2021-08-22 03:41 UTC, buzri1905 commented on codes/1963_cpp_wodnjs.cpp
> +			for (int j = 2 * i; j < 10000; j += i)
i * i로 고치면 사실상 같은 코드인데 더 효율적으로 작동합니다.
```suggestion
			for (int j = i * i; j < 10000; j += i)
```

2021-08-22 03:41 UTC, buzri1905 commented on codes/1963_cpp_wodnjs.cpp
> +		}
자리수별로 for문을 돌리기 보다
for(자릿수)
   for(바꿀 수)
이렇게 짜주세요

2021-08-22 07:22 UTC, resource777 commented on codes/1963_cpp_wodnjs.cpp
> +		}
자리 수마다 로직이 조금씩 다른데 일반화 할 수 있는 방법이 있을까요?

2021-08-22 08:38 UTC, buzri1905 commented on codes/1963_cpp_wodnjs.cpp
> +		}
맨 앞자리 수가 0이 아니여야한다는 것이라면 조건문에 1000이상의 수라는 것을 추가하거나 1000미만의 수에 대해서 vis를 -1와 같은 수를 채워 넣으면 됩니다.

간략하게 코드 예시를 보여드리자면 현재 숫자를 num이라 하면
```suggestion
		for(int digit = 1; digit <= 1000; digit *= 10){
		    int digit_ num = (num / digit) % 10;
		    for(int i=0; i <=9; i++){
		        if(digit_num == i)
		            continue;
		        int next_num = num - digit_num * digit + i * digit;
```

2021-09-03 13:31 UTC, buzri1905 requested changes
자릿수 일반화가 아직 안되었습니다.

2021-09-04 06:37 UTC, resource777 commented
> 자릿수 일반화가 아직 안되었습니다.

방금 수정해서 올렸는데 제대로 됐는지 확인해주시면 감사하겠습니다.!

2021-09-04 13:20 UTC, buzri1905 approved these changes
피드백 확인해주세요. 수정이 필요한 것은 아니여서 바로 머지하겠습니다.

2021-09-04 13:20 UTC, buzri1905 commented on codes/1963_cpp_wodnjs.cpp
> +			int digit_num = (front_num / digit) % 10;
괄호는 없어도 됩니다.

2021-09-04 13:20 UTC, merged

2021-09-04 13:20 UTC, buzri1905 commented
머지했습니다.