저번주거 두문제 업로드하였습니다 ㅜㅜ 죄송합니당
buzri1905/algo_study pull request #9
Opened 2021-08-22 10:59 UTC by JunTae-Kim-code

에라토스체문제, 벽부수고 이동 추가

2021-08-23 14:48 UTC, buzri1905 requested changes
피드백 반영해주세요.
2023번 풀이는 인상깊었습니다. 잘푸셨어요

2021-08-23 14:48 UTC, buzri1905 commented on codes/12865_py3_sjskgks.py
> +print(knapsack[-1][-1])
공간복잡도 개선해주세요.
공간 복잡도는 O(limit)으로 구현가능합니다.
시간복잡도도 지금은 O(numOfthings * limit)으로 되어있는데 O(numOfthings^2 * log numOfthings)로 개선가능합니다. (시간복잡도는 원하시면 바꿔보세요)

2021-08-23 14:48 UTC, buzri1905 commented on codes/12865_py3_sjskgks.py
> +numOfthings, limit = map(int, input().split())
보통 대문자를 섞어서 네이밍 할때는 제일 앞 글자를 제외하고 의미마다 대문자를 씁니다. 그런데 꼭 반영할 필요는 없습니다.(반드시 지켜야할 규칙은 아니여서)
```suggestion
numOfThings, limit = map(int, input().split())

```

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +    for i in range(2, m + 1):
** 연산은 느리고, 소수가 중간에 나오기 때문에 소숫점 관련 문제가 생길 수 있습니다.
```suggestion
    for i in range(2, n + 1):
        if i * i > n:
            break
```

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
i*i부터 보면 더 효율적입니다.
```suggestion
            for j in range(i*i, n, i): # i이후 i의 배수들을 False 판정
```

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +    visit = [0 for _ in range(10000)]
testcase마다 큰 배열을 초기화한다면 비효율적일 것입니다.
visit을 for문 밖에서 선언하고 초기화를 하지 않고 사용하는 방법을 고안해보시겠어요?
도전과제로 생각해주세요 반드시 구현해야하는 사항은 아닙니다.

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +    flag=0
flag보다 isReached와 같은 변수명이 더 알아보기 쉬울 것 같습니다.(또한 0, 1보다 True, False로 판단하는게 더 좋아보입니다.)

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +        for num in thousand_overlist:
모든 소수를 다 확인하는 것은 시간복잡도 적으로 좋은 방법이 아닌 것 같습니다. 수정해주세요

2021-08-23 14:48 UTC, buzri1905 commented on codes/1963_py3_sjskgks.py
> +            sub_num = str(num)
str로 바꿔서 판단하기보다 int연산으로 판단해주세요

2021-08-23 14:48 UTC, buzri1905 commented on codes/2023_py3_sjskgks.py
> +N=int(input())
문제에서 주어진 변수여도 변수명을 이쁘게하면 더 좋을 것 같습니다

2021-08-23 14:48 UTC, buzri1905 commented on codes/2023_py3_sjskgks.py
> +        division=0
이것도 true, false변수로 하면 좋을 것 같습니다.

2021-08-23 14:48 UTC, buzri1905 commented on codes/2206_py3_sjskgks.py
> +            next_row, next_col = next_idx
```suggestion
        for next_row, next_col in [[cur_r-1,cur_c],[cur_r+1,cur_c],[cur_r,cur_c-1],[cur_r,cur_c+1]]:
```

2021-08-23 14:48 UTC, buzri1905 commented on codes/2206_py3_sjskgks.py
> +            if next_row<row and -1<next_row and next_col<col and -1<next_col:
이러면 아래에 indent가 전부 하나씩 추가되므로
```suggestion
            if next_row >= row or 0 > next_row or next_col >= col or 0 > next_col:
                continue
```
로 바꾸고 아래 인덴트를 하나씩 줄이는 것이 좋습니다.

2021-08-23 14:48 UTC, buzri1905 commented on codes/2437_py3_sjskgks.py
> +    print(can_create_weight+1)
어차피 can_create_weight + 1을 출력하므로 flag가 필요없을 것 같습니다.
```suggestion
for cur_chu in chus:
    if cur_chu>can_create_weight+1: # 현재 만들어야하는 추 수: can_create_weight+1, 다음추가 이거보다 크면 해당 추 못만듦
        break
    can_create_weight+=cur_chu # 0~can_create_weight만큼 만들수 있고 새로 추가 추가됐으므로 0~can_create_weight+cur_chu만큼 조합으로 생성 가능
print(can_create_weight+1)
```

2021-08-23 14:48 UTC, buzri1905 commented on codes/2529_py3_sjskgks.py
> +    flag = 0
flag라는 이름보다 더 좋은 이름으로 고쳐주세요

2021-08-23 14:48 UTC, buzri1905 commented on codes/9184_py3_sjskgks.py
> +    print('w({:d}, {:d}, {:d}) = {:d}'.format(a, b, c, answer))
메모이제이션을 이용해 필요한 값만 계산하도록 고쳐보시겠어요?
사실 이렇게 풀어도 되지만 이 문제를 통해 배우고자 하는 게 메모이제이션이여서요....

2021-08-28 12:45 UTC, closed without merging

2021-08-28 12:45 UTC, sjskgks commented
im sorry